truncate table AuditRecords
truncate table Dashboards
truncate table Datasets
truncate table Dataflows
truncate table DataflowDatasources
truncate table Datasources
truncate table DevTokens
truncate table EmbedCodes
truncate table Gateways
truncate table LicensesOrg
truncate table LicensesUsers
truncate table LicensesUsersPro
truncate table PowerBITenant
truncate table PremiumCapacities
truncate table PremiumDatasetInfo
truncate table PremiumDataSetSize
truncate table PremiumEvictionMetrics
truncate table PremiumQueryMetrics
truncate table PremiumSystemMetrics
truncate table RefreshHistory
truncate table Reports
truncate table TenantSettings
truncate table Workspaces
truncate table WorkspaceUsers